name: GitHub Actions
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch on Push and any branches on PR
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Set NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: node --version
      - run: pnpm --version

      - name: Run pnpm install dependencies
        run: pnpm install

      - name: Website Prod Build (GitHub demo site)
        run: |
          cd standalone-with-translate
          pnpm run build

      # always deploy (re-publish) GitHub demo page with a Prod build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./standalone-with-translate/dist
