name: GitHub Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
env:
  CI: true

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./standalone-with-translate

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: standalone-with-translate/package-lock.json

      - run: node --version
      - run: npm --version

      # Use 'npm ci' for faster, reliable builds in CI environments
      - run: npm ci --force

      - name: Website Prod Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./standalone-with-translate/dist
